GET http://127.0.0.1:8000/api/candidates HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer nvdksk24q249unbd

###

POST http://127.0.0.1:8000/api/users HTTP/1.1
content-type: application/json

{
    "first_name": "MR Dj",
    "last_name": "Alligator",
    "email": "somegreatbobr@gmail.com",
    "password": "yfAE89!!Nv8",
    "age": 32
}

###

POST http://127.0.0.1:8000/api/users/login HTTP/1.1
content-type: application/json
Accept: application/json

{
    "email": "mytester237@mail.com",
    "password": "!!11QQwas"
}