GET http://127.0.0.1:8000/api/candidates HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RfbmFtZSI6Ik15IiwibGFzdF9uYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJteXRlc3RlcjIzN0BtYWlsLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDIyLTA5LTE4VDEzOjM4OjM0LjAwMDAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMi0wOS0xOFQxMzozODozNC4wMDAwMDBaIiwiYWdlIjoyNH0sImlhdCI6MTY2MzUwODMyNiwiZXhwIjoxNjYzNTA5MjI2fQ.aY95it5Y6v1_ANutgM2RBUYt5ORntmZjiWpiR_wewN4

###

POST http://127.0.0.1:8000/api/users HTTP/1.1
content-type: application/json
Accept: application/json

{
    "first_name": "MR Dj",
    "last_name": "Alligator",
    "email": "somegreatbobr@gmail.com",
    "password": "yfAE89!!Nv8",
    "age": 32
}

###

POST http://127.0.0.1:8000/api/users/login HTTP/1.1
content-type: application/json
Accept: application/json

{
    "email": "mytester237@mail.com",
    "password": "!!11QQwas"
}

###

POST http://127.0.0.1:8000/api/users/refresh HTTP/1.1
content-type: application/json
Accept: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTEsImlhdCI6MTY2MzUwODMyNiwiZXhwIjoxNjY2MTAwMzI2fQ.VPsL82nCUCZsK-XEZYOFrMxpwMfi2_5R_bPVP-25J1I"
}

###

POST http://127.0.0.1:8000/api/users/logout HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RfbmFtZSI6Ik15IiwibGFzdF9uYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJteXRlc3RlcjIzN0BtYWlsLmNvbSIsImFnZSI6MjR9LCJpYXQiOjE2NjM3MTIxNTEsImV4cCI6MTY2MzcxMzA1MX0.Fe3T1YB9tBsK3hgDZkDX5OQ5doa31M60e9X_Cy7TDF8

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTEsImlhdCI6MTY2MzcxMjE1MSwiZXhwIjoxNjY2MzA0MTUxfQ.pYrmAEYXyPPBDN5jlmhNPyqlp7jrZE3CEa13AcXrqnI"
}

###

POST http://127.0.0.1:8000/api/candidates HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RfbmFtZSI6Ik15IiwibGFzdF9uYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJteXRlc3RlcjIzN0BtYWlsLmNvbSIsImFnZSI6MjR9LCJpYXQiOjE2NjQ1NDEyMTAsImV4cCI6MTY2NDU0MjExMH0.yhP9JKEWjrg9RS-II_LhIfqOMiTKjt36-42q-Xh-PBQ
Accept: application/json

{
    "experience": 1,
    "position": "Very good employee",
    "city": "Tokyo",
    "portfolio": "https://github.com/Ibarsuk",
    "text": "Some large text"
}